### ISSUE TITLE
makeShinyApp

### ISSUE THREAD

**Issue by afcmalone** [SGDDNB/ShinyCell#1]
Hi,

I am trying to run makeShinyApp on my seurat object.
It is an integrated object - not sure if that is causing the erroe.

makeShinyApp(seu, scConf, gene.mapping = TRUE, 
             gex.assay = "RNA", gex.slot = "data",
             shiny.title = "ShinyCell Tutorial",
             shiny.dir = "shinyApp/", shiny.footnotes = footnote)
Error in !all.equal(sc1meta$sampleID, gex.colnm) : invalid argument type
Registered S3 method overwritten by 'cli':
  method     from    
  print.boxx spatstat

Any ideas?

Thanks

**Comment by jfouyang** [comment]
Hi,

When running `makeShinyApp()`, the functions does a few checks on the Seurat object and it raises an error when the checks fail. In particular, the error you got is due to a mismatch between the rownames in the metadata (`sc1meta$sampleID`) and the colnames in the gene expression (`gex.colnm`). I have not encountered this problem previously for both RNA and integrated objects. By any chance, have you subsetted the Seurat object before?

Also, you mind helping me run the following lines to do some checks?
`gex.colnm = colnames(slot(seu@assays[["RNA"]], "data"))`
`all.equal(gex.colnm, rownames(seu@meta.data))`

And also this:
`gex.colnm = colnames(slot(seu@assays[["integrated"]], "data"))`
`all.equal(gex.colnm, rownames(seu@meta.data))`

In the meantime, I will try to implement a workabout if this issue persists. :)

**Comment by afcmalone** [comment]
Thank you for the prompt reply.

I tried makeShinyApp() on both an integrated object subsequently subsetted
and a second integrated object not subsetted..

I ran the code you mentioned (which i have run previously in an effort to
fissure the error out).
see below:

> gex.colnm = colnames(slot(seu@assays[["RNA"]], "data"))
> all.equal(gex.colnm, rownames(seu@meta.data))
[1] "9845 string mismatches"
> gex.colnm = colnames(slot(seu@assays[["integrated"]], "data"))
> all.equal(gex.colnm, rownames(seu@meta.data))
[1] "9845 string mismatches"

Thanks,
Andrew Malone

**Comment by jfouyang** [comment]
As mentioned earlier, the `gex.colnm` and `rownames(seu@meta.data)` are the cell barcodes and should match. Can you help me run the following code so I can take a look at some of the cell barcodes?

`gex.colnm = colnames(slot(seu@assays[["RNA"]], "data"))`
`head(gex.colnm)`

`gex.colnm = colnames(slot(seu@assays[["integrated"]], "data"))`
`head(gex.colnm)`

`head(rownames(seu@meta.data))`

Also, can you run the following so I can check if the dimensions are correct as well?
`dim(slot(seu@assays[["RNA"]], "data"))`
`length(rownames(seu@meta.data))`

**Comment by afcmalone** [comment]
Sorry about that,
I should have added.

gex.colnm = colnames(slot(seu@assays[["RNA"]], "data"))
> head(gex.colnm)
[1] "AACACGTCAGCGTCCA-1_1" "AACACGTCATGATCCA-1_1" "AACACGTGTCCGTTAA-1_1"
[4] "AACCATGAGCGTCAAG-1_1" "AACCATGCAACCGCCA-1_1" "AACCATGCAAGTTCTG-1_1"
>
> gex.colnm = colnames(slot(seu@assays[["integrated"]], "data"))
> head(gex.colnm)
[1] "AACACGTCAGCGTCCA-1_1" "AACACGTCATGATCCA-1_1" "AACACGTGTCCGTTAA-1_1"
[4] "AACCATGAGCGTCAAG-1_1" "AACCATGCAACCGCCA-1_1" "AACCATGCAAGTTCTG-1_1"
>
> head(rownames(seu@meta.data))
[1] "AAACCTGAGAAACGAG-1_5" "AAACCTGAGACGCTTT-1_5" "AAACCTGAGCCGGTAA-1_5"
[4] "AAACCTGAGTGGAGAA-1_2" "AAACCTGCAGACAAGC-1_5" "AAACCTGCAGCTTCGG-1_2"
> dim(slot(seu@assays[["RNA"]], "data"))
[1] 18039  9845
> length(rownames(seu@meta.data))
[1] 9845

It looks like the order of the cell barcodes are different but all the
same. I checked the whole barcode list.

Thanks
Andrew

**Comment by afcmalone** [comment]
Hi,

I added the following and the error went away.

sc1meta_order <- sc1meta[match(gex.colnm_rna, sc1meta$sampleID),]
after line 60 - 'sc1meta = data.table(sampleID = rownames(obj@meta.data),
obj@meta.data)

however now i get there error:
> makeShinyApp(seu, scConf, gene.mapping = FALSE,
+              gex.assay = "RNA", gex.slot = "data",
+              shiny.title = "pbmc Dataset",
+              shiny.dir = "pbmc/", shiny.footnotes = NULL)
Error in write_file_(x, file) : Expected string vector of length 1
In addition: Warning message:
In makeShinyFiles(obj = obj, scConf = scConf, gex.assay = gex.assay[1],  :
  Variable genes not found! Did you use specify the wrong assay or wrong
seurat object?

Thanks,
Andrew

**Comment by afcmalone** [comment]
line 69 of makeShinyFiles.R - sorry

**Comment by jfouyang** [comment]
Hi Andrew,

I have modified the code for `makeShinyApp` to account for situations to match the cell barcodes in the metadata and in the gene expression. You mind reinstalling the package and rerun the pipeline?

As for the warning message, it happens when you use the "RNA" assay from an integrated Seurat object. ShinyCell is finding highly variable genes as default genes for the shiny app and the highly variable gene information is absent in the "RNA" assay for an integrated object. To prevent this warning, you can use `gex.assay = "integrated"` instead.

John

**Comment by afcmalone** [comment]
HI John,
Thanks for correcting this error. I reinstalled and the old error is gone.
I used gex.assay = "integrated" but still get the same error 'Error in
write_file_(x, file) : Expected string vector of length 1'

Andrew

**Comment by jfouyang** [comment]
Hi Andrew,

Can I check if the error occurs when you run `makeShinyApp()`? Or some other function like `makeShinyCodes()`? I am asking this because I cannot find the corresponding code in the function.

I am not exactly sure where the error is coming from but one guess for now is that the `readr` package that you are using might be a bit too old. You mind updating the `readr` package by running `install.packages("readr")` and see if the error goes away?

John

**Comment by afcmalone** [comment]
Hi John,,

I reinstalled readr and the error still occurs, readr is 1.4.
Not sure what you are asking me to do in running makeShinyApp() or
makeShinyCodes()

makeShinyApp(seu, scConf, gene.mapping = FALSE,
+              gex.assay = "integrated", gex.slot = "data",
+              shiny.title = "Dataset",
+              shiny.dir = "biopsyint/", shiny.footnotes = NULL)
Error in write_file_(x, file) : Expected string vector of length 1


not sure what arguments to enter for makeShinyCodes() function

Andrew

**Comment by afcmalone** [comment]
Hi John,

I have managed to get this working. there was an error in one of my file
paths causing the:
Error in write_file_(x, file) : Expected string vector of length 1

thank you for you help

Andrew

**Comment by jfouyang** [comment]
Hey! Glad that things worked out in the end. Thanks again for using ShinyCell!
