### ISSUE TITLE
createConfig error for SCE object

### ISSUE THREAD

**Issue by carissaynchen** [SGDDNB/ShinyCell#11]
Hello, I think this is a really great package! but I'm having issue with the `createConfig(sce)` command. I've followed the tutorial steps as below:

`seu <- readRDS("readySeu_rset.rds")`
`sce <- as.SingleCellExperiment(seu)`
`scConf = createConfig(sce)`

and this error appears `Error in createConfig(sce) : 
  no slot of name "reducedDims" for this object of class "SingleCellExperiment"`

despite there are five objects: PCA TSNE UMAP DIFFMAP FDL in the example data. How should I solve this error?

**Comment by jfouyang** [comment]
Hi! Thanks for using the package!

It seems that you are getting the errors because the internals of the SingleCellExperiment object has changed in the past few months. I have just updated a "patch" onto the github repository which should access the SCE object properly now. Can you reinstall ShinyCell and check if the error disappears?

If everything is ok, maybe you can drop me a reply here and I will then close the issue.

**Comment by carissaynchen** [comment]
I have reinstalled ShinyCell and run the code as above but when I reach createConfig this error appears:

`internal error -3 in R_decompress1Error: lazy-load database '/Users/carissaynchen/Library/R/4.0/library/ShinyCell/R/ShinyCell.rdb' is corrupt`

**Comment by jfouyang** [comment]
This "lazy-load database corrupt" error seems pretty common when you try to reinstall packages. 
An example I found is in https://github.com/lme4/lme4/issues/407

1. It seems that restarting your R completely can solve that problem.

2. If that fails, please restart R again and uninstall the package by running `remove.packages("ShinyCell")` and then install ShinyCell again.

Hope this helps.

**Comment by carissaynchen** [comment]
Yes, everything works fine now! thank you
