### ISSUE TITLE
Gene expression not shown for genes with short gene names 

### ISSUE THREAD

**Issue by ankushs0128** [SGDDNB/ShinyCell#19]
Hi , 

The shiny cell is not showing genes showing expression in RDS file. 
see Screen shot enclosed.  
<img width="559" alt="Screenshot 2021-07-05 at 12 14 12" src="https://user-images.githubusercontent.com/32255128/124456144-a9448f00-dd8a-11eb-8fcf-3186d6afd831.png">

<img width="376" alt="Screenshot 2021-07-05 at 12 09 02" src="https://user-images.githubusercontent.com/32255128/124456140-a8136200-dd8a-11eb-821e-e2f309b506af.png">

Any help appreciated

**Comment by jfouyang** [comment]
From what I gathered, this problem occurs when the gene name is too short. Consequently, the search bar will display any genes where there is a partial match in the name. And since the search bar only displays a small number of search hits, the gene you are looking for cannot be selected.

To address this, I have modified the code in ShinyCell to display shorter gene names first.
Can you install the current version of ShinyCell and tell me if the problem is resolved?

And thanks for using ShinyCell!

**Comment by mdidish** [comment]
@jfouyang Thank you for the update, it works like a charm and it is very useful! (for example to display Tnf gene, one of our favorite gene!).

**Comment by jfouyang** [comment]
Glad that the update works and that ShinyCell is helping in analysing / visualising your single-cell data!

**Comment by ankushs0128** [comment]
Thanks @jfouyang ,  It works!
