### ISSUE TITLE
meta.to.del not found in shinycell config!

### ISSUE THREAD

**Issue by shamsbhuiyan** [SGDDNB/ShinyCell#22]
I would like to delete some metadata from the shinycell output. I tried running the following code:

```
m_scConf = createConfig(mouse)
m_scConf<-delMeta(m_scConf,c("orig.ident","RNA_snn_res.1.5","seurat_clusters","tSNE_1","tSNE_2","UMAP_1","UMAP_2","sample","library_date","sample_date",
                             "donor","library_ID","RNA_snn_res.1","PC1","PC2","PC3","PC4","PC5","tSNE1","tSNE2","UMAP1","UMAP2"))
```

When I run this command, I get the following error:
```
Error in delMeta(m_scConf, c("orig.ident", "RNA_snn_res.1.5", "seurat_clusters",  : 
  meta.to.del not found in shinycell config!
```

What is causing this error?

**Comment by jfouyang** [comment]
Hi. First of all, many apologies for the late reply. It has been a busy period finishing some projects and taking vacation.

I believe that the error is due to an attempt to remove the dimension reduction coordinates e.g. `"tSNE1","tSNE2","UMAP1","UMAP2"`. These dimension reduction coordinates are automatically added by ShinyCell so that the dimension reduction coordinates are retrieved properly when plotting.

I think the error should go away when you get rid of the dimension reduction coordinates e.g. 
```
m_scConf = createConfig(mouse)
m_scConf<-delMeta(m_scConf,c("orig.ident","RNA_snn_res.1.5","seurat_clusters","sample","library_date","sample_date",
                             "donor","library_ID","RNA_snn_res.1"))
```

Hope this helps!

**Comment by shamsbhuiyan** [comment]
Hey thank you for responding. I hope your vacation went well and yes, that did fix the error! I'll close the issue.
