### ISSUE TITLE
Split violin plot, differential gene expression, naming clusters

### ISSUE THREAD

**Issue by mahadevanv** [SGDDNB/ShinyCell#24]
Hi there, 
This is a great tool. I am looking to see if there are any upcoming updates for the following:
1. split-violin plots to simultaneously show gene expressions across clusters
2. Volcano plots to show differential expression within clusters that are part of the Seurat object.
3. Also, I have renamed the clusters (instead of 0,1,2...) and saved them in the Seurat object, but they do not appear in the  Shinycell app. Has anyone observed this, or how could we correct this?
Thanks in advance,
Viv

**Comment by jfouyang** [comment]
Hi Viv, regarding your questions,

1. Split-violin plots will be useful but there are currently no plans to add new features to ShinyCell at least for the next two months. But this will definitely be on the top of the list when I have time to add new features!

2. Incorporating DE volcano plots can be quite cumbersome for several reasons. First, the DE results from FindAllMarkers and FindMarkers function in Seurat are not stored within the Seurat object but as a separate data.frame. This is not surprising given that you can perform DE in a variety of ways e.g. finding markers across libraries or across clusters. Loading all the various objects is difficult to automate and we want to keep ShinyCell as easy to operate as possible. Second, users may choose to use other DE tools e.g. MAST / DESeq2 instead of the Wilcoxon test in Seurat. These different tools will generate different outputs, which is hard to standardize. That said, users can add custom tabs into their shiny apps to perform additional visualization, i.e., DE volcano plots in your situation. I will provide some R code in the reply below to do so.

3. As a quick check, can you check if the renamed clusters can be accessed via `seu$newclusters`? Also, the renamed clusters needs to be factored i.e. `seu$newclusters = factor(seu$newclusters)`. If the metadata is not factored, ShinyCell will not be able to process it properly.

**Comment by jfouyang** [comment]
If you would like to manually add the DE volcano plots, I have prepared some code here.

First, I assume that you have ran `FindAllMarkers` and wrote the output into the same folder as the shiny app: 
```
inpMarkers = FindAllMarkers(seu)
fwrite(inpMarkers, sep = "\t", file = "inpMarkers.txt")
```

Inside `ui.R`, you need to add the following code to create an interface for you to change settings:
```
             div(style="display:inline-block", 
                 numericInput("sc1d1oup.w", "PDF / PNG width:", width = "138px", 
                              min = 4, max = 20, value = 10, step = 0.5)) 
      )  # End of column (6 space) 
    )    # End of fluidRow (4 space) 
  )      # End of tab (2 space) 
   ,    

##### START OF NEW CODE TO ADD #####
### Tab1.x1: New tab for slingshot
tabPanel( 
  HTML("DE Volcano Plot"), 
  h4("DE Volcano Plot"), 
  "In this tab, users can visualise the volcano plot for marker gene differential expression.",
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      selectInput("sc1de1inp", "Cluster", choices=NULL)
    ), # End of column (6 space) 
    column(9, plotOutput("sc1de1oup") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
),     # End of tab (2 space) 
##### END OF NEW CODE TO ADD #####

br(), 
p("", style = "font-size: 125%;"), 
p(em("This webpage was made using "), a("ShinyCell", 
  href = "https://github.com/SGDDNB/ShinyCell",target="_blank")), 
br(),br(),br(),br(),br() 
))) 
```

Then, in `server.R`, you need to add a new function to plot the volcano plot:
```
  inpMarkers = fread("inpMarkers.txt")
  updateSelectizeInput(session, "sc1de1inp", choices = unique(inpMarkers$cluster), server = TRUE, 
                       selected = unique(inpMarkers$cluster)[1], options = list( 
                       maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) 
  
  output$sc1de1oup <- renderPlot({ 
    ggData = inpMarkers[cluster == input$sc1de1inp]
    ggData[p_val_adj < 1e-300]$p_val_adj = 1e-300
    ggData$log10fdr = -log10(ggData$p_val_adj)
    ggplot(ggData, aes(avg_log2FC, log10fdr)) + 
      geom_point() + sctheme() + ylab("-log10(FDR)")
  }, height = 450, width = 600) 
```

**Comment by jfouyang** [comment]
Closing the issue to inactivity.

**Comment by Cailu086Lin** [comment]
This is very helpful. 
How to add code to download the pdf and png for DE volcano?

I tried to add the ui.R
####
downloadButton("renderDataTable.pdf", "Download PDF"),  
           downloadButton("sc1de1oup.png", "Download PNG"), br(), 
           div(style="display:inline-block", 
               numericInput("sc1de1oup.h", "PDF / PNG height:", width = "138px", 
                            min = 4, max = 20, value = 8, step = 0.5)), 
           div(style="display:inline-block", 
               numericInput("sc1de1oup.w", "PDF / PNG width:", width = "138px", 
                            min = 4, max = 20, value = 10, step = 0.5))
####
but not sure what are needed for server.R

Thanks
