### ISSUE TITLE
Disabling Toggle to show cell numbers/statistics

### ISSUE THREAD

**Issue by dKlee99** [SGDDNB/ShinyCell#26]
Hi, 

Is there any functions to disable "Toggle to show cell numbers/statistics"? Thank you very much for your help!

Best,
DK

**Comment by jfouyang** [comment]
In principle, you can remove the other buttons in the same way. _But_ I would _discourage_ disabling the "toggle plot control" and "toggle graphics control" buttons.

The "toggle plot control" allows users to change the colour palette (which is useful since certain colour palettes might be better for some metadata) and plotting order (which is useful to visualise points that are densely packed on the UMAP plot which may block other points).

The  "toggle graphics control" allows users to change the plot size and point size. We find this very helpful as users may be browsing the shiny app from different devices. For example, you might want a larger plot size and larger points on a widescreen monitor or a smaller plot and point size if you are browsing on a mobile / laptop.

These features are designed to make it comfortable to browse the shiny app, which encourages people to browse your data (which will hopefully increase its citation etc).
