### ISSUE TITLE
missing option for "NA" in "Toggle to subset cells"

### ISSUE THREAD

**Issue by ersgupta** [SGDDNB/ShinyCell#33]
Hi, would it be possible to include the "NA" values as well in "Toggle to subset cells"? I have some rows which contain NAs for some columns. I do not see the option to remove such cells using Toggle.

Thanks
Saurabh

**Comment by jfouyang** [comment]
Hi Saurabh,

First of all, much apologies for the slow response.

I believe that the "NA" values are automatically omitted by R in general which is why it is not shown in the "Toggle to subset cells". Perhaps you want to rename the "NA" values to some character string e.g. "nil" so that it can be recognised by R? This might be a much easier fix.

John

**Comment by jfouyang** [comment]
Closing the issue to inactivity.
