### ISSUE TITLE
Poor quality text on plots

### ISSUE THREAD

**Issue by royfrancis** [SGDDNB/ShinyCell#36]
Here is a preview of what I see running a test app locally on my system. Note the low quality text on the plots.

![Screenshot from 2022-01-24 17-20-48](https://user-images.githubusercontent.com/5083500/150822239-343a164f-0d53-4065-8698-4daedcf56764.png)

And here is a closer look at one of the figures.

![Screenshot from 2022-01-24 17-23-18](https://user-images.githubusercontent.com/5083500/150822511-bb2bbef4-f5b8-447d-bee7-82532af25770.png)

Notice how the text elements on the plot are of low quality. Looks like they have low resolution or something. But, the other elements seems to be fine. And it's the same across all plots. I was wondering if you might have some insight into what's happening? Something to do with fonts?

In addition, downloaded plots do not have this issue but they have weird text scaling/size. See below:

![sc1UMAP1_UMAP2_seurat_clusters](https://user-images.githubusercontent.com/5083500/150823803-7c3e348e-bc71-45d8-a44b-54c89b2c76c7.png)

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS
ggplot2_3.3.5
```

**Comment by jfouyang** [comment]
Hi Roy,

Regarding the "low quality text" on the shiny app itself, it could be a Shiny package issue since the image needs to be rendered quickly for interactive browsing. Thus, I do not have any control over it.

As you pointed out, downloaded plots should have better text quality. The plots are rendered using ggplot2 and the text is generated using `geom_text_repel` using default settings. So again, I do not have much control over changing the quality of the text rendered.

John

**Comment by royfrancis** [comment]
Text quality/rendering issue resolved by changing `renderPlot()` to `renderImage()`.
