### ISSUE TITLE
Not all genes present ?

### ISSUE THREAD

**Issue by baracus37** [SGDDNB/ShinyCell#7]
Hi,

thanks for this fantastic tool, it makes working with our collaboration partners so much easier. 

However, I noticed that for one dataset I can plot the expression of a certain gene in Seurat. After creating the ShinyCell App I can not select this gene in the Shiny App. Are not all genes from a dataset exported to the App?

Best,

**Comment by jfouyang** [comment]
Glad that the tool is helpful in your single-cell work. :)

By default, ShinyCell takes the log-transformed normalised gene expression from the RNA assay, which you can access using `slot(seu@assays[["RNA"]], "data")` where `seu` is your seurat object.

Can you run this code to check if your intended gene is in that gene expression matrix?
`"your-gene-of-interest" %in% rownames(slot(seu@assays[["RNA"]], "data"))`

Also, another possibility is that ShinyCell automatically maps Ensembl geneIDs to gene symbols and that may have altered your gene names. To disable that, set `gene.mapping = FALSE` in the code below: 
```
makeShinyApp(seu, scConf, gene.mapping = FALSE,
             shiny.title = "ShinyCell Quick Start") 
```

**Comment by Boyson-Lab** [comment]
> thanks for this fantastic tool, it makes working with our collaborationspertner so much easier.
>

I will second that-- wonderful tool! I am having a similar issue except that I am only seeing about 5 genes. I've used your code and all genes are indeed present in the object. I am getting this error:

**Variable genes for seurat object not found! Have you ran `FindVariableFeatures` or `SCTransform`?**

 after running `makeShinyApp(seu, scConf, gene.mapping = FALSE, gex.assay = "integrated", shiny.title = "ShinyCell test") .`  

I've tried substituting RNA and SCT in the `gex.assay =` line and received the same error. I checked the integrated assay and there are indeed genes present in the var.features slot. 

Thanks for any help--

**Comment by baracus37** [comment]
> Can you run this code to check if your intended gene is in that gene expression matrix?
> `"your-gene-of-interest" %in% rownames(slot(seu@assays[["RNA"]], "data"))`

Running this code retuns `TRUE`, so it is present. I have also tried setting `gene.mapping = FALSE`, but this did not resolve the issue. 

> Variable genes for seurat object not found! Have you ran FindVariableFeatures or SCTransform?

I am getting the same error message. I forgot to mention this, sorry!
I usually normalize via SCT, then run integration and clustering (UMAP) an subsequently run `NormalizeData` and `ScaleData` on the RNA Assay for Marker discovery and Plotting.

**Comment by jfouyang** [comment]
Yes it definitely helps to know that SCT and integration was performed as I wasn't expecting that :) Anyways,  there seem like there are several issues here which I will address:

1. I am only seeing about 5 genes...
If you click on the "Gene name:" dropdown, you will only see 5 genes which happened to be the top 5 genes alphabetically. All the genes in the assay should be available for plotting. Try clicking in the dropdown box, press backspace and start typing the gene of interest, the gene name will then try to autocomplete itself, showing the top 5 options. You can then pick a gene from the autocomplete options or continue to type the full gene name and press enter.

2. The warning about "Variable genes for seurat object not found!"
First, this is a warning (and not an error) so the ShinyCell app will still be generated. Basically, ShinyCell looks for the top variable genes to be used as default genes for plotting. It runs `VariableFeatures(seu)` in the backend and picks the first few genes. So you will only get this warning if `VariableFeatures(seu)` returns no genes. I tried it on a SCT-transformed Seurat-integrated object myself and I am still able to retrieve the variable genes and not get error. So maybe you all can try running `VariableFeatures(seu)` and tell me if it returns any genes. I would not be too concerned with this warning as the app will still be generated and you can always specify the default genes yourself (to some gene that you plotted in the paper perhaps).

3. Which assay to use if I normalize via SCT and do Seurat integration?
So if you normalize via SCT and do Seurat integration, there will be three assays:
(i) `"RNA"` assay which contains the raw counts since SCT is used
(ii) `"SCT"` assay which contains the SCT-transformed expression prior to integrated
(iii) `"integrated"` assay which contains the integrated gene expression
Please do not use the `"RNA"` assay in this case as the raw counts are not log-transformed. So please use either the `"SCT"` or `"integrated"` assay in the `gex.assay` argument as mentioned by @Boyson-Lab. Note that the `"integrated"` assay only contains 3000 genes i.e. the genes used for integration instead of all detected genes. So if you are using the integrated assay, please check if `"your-gene-of-interest" %in% rownames(slot(seu@assays[["integrated"]], "data"))`

I hope I have covered everything. If I miss anything, maybe you can open it as a new issue as the thread here is pretty congested already.

**Comment by Boyson-Lab** [comment]
Thanks-- that's all I needed. Works beautifully!

**Comment by baracus37** [comment]
Thanks for your explanations. However using the SCT assay doe snot change the issue that I am having. 

I am looking for the gene Tnf. This is present in the dataset in both RNA and SCT assay:

`> "Tnf" %in% rownames(slot(GE.335.2.integrated@assays[["RNA"]], "data"))
[1] TRUE`
`> "Tnf" %in% rownames(slot(GE.335.2.integrated@assays[["SCT"]], "data"))
[1] TRUE`

But when trying to select it in the Gene name dropdown only other genes containing the string "tnf" are shown:
![20210420_102829_resized_2](https://user-images.githubusercontent.com/22492277/115366420-9c6dc180-a1c5-11eb-9582-5ea8eb9d1663.jpg)
(Apologies for the phone picture, but as soon as I am taking a screenshot, the drop-down disappears.)

So I assume that sorting is somehow not working in this case as I would expect genes starting with "Tnf" should appear at the top of the list. As soon as I type "Tnfa" genes starting with "Tnf" are suddenly appearing in the list. 
![20210420_103349_resized2](https://user-images.githubusercontent.com/22492277/115366393-9841a400-a1c5-11eb-9cfd-c847ca0b70fc.jpg)

**Comment by jfouyang** [comment]
Hi @baracus37, 

No worries about the phone screenshot. It helps in the troubleshooting :)

I think this is the way that autocomplete works in Shiny/javascript in general. It will search for any gene that contains the text you entered. So when you enter "Tnf", the C1qtnf* genes are found and they are shown at the top as they are alphabetically ahead of "Tnf". If you want to plot "Tnf", you can press the Enter key after typing "Tnf" to input the text and it should plot the gene. Is that working in your case?

**Comment by baracus37** [comment]
Hi,

Thanks for the tip. This is working! However, the first hit from the dropdown is automatically selected. So one would have to make sure that no entry from the dropdown is selected. 
Interestingly, after I have once plotted Tnf, if I reenter Tnf into the search field, it will now show in the dropdown menu, just as if it remembered my previous searches.

**Comment by jfouyang** [comment]
The dropdown will only show the top 5 nearest matches so I don't think it needs to be scrollable? I think it all boils down to an unfortunate case that the text you are searching for (i.e. Tnf) happens to be present in multiple gene names namely the C1qtnf* genes. 

So I guess that I will close the issue for now as all the genes are present. :)

**Comment by shamsbhuiyan** [comment]
Apologies for reopening this issue, but I was just wondering if there is a way to change from the top 5 genes being displayed to the top 10 genes? Or maybe just to add the instruction like "Type in gene" next to the dropdown box? Otherwise I think it looks like only 5 genes are present in the data

**Comment by jfouyang** [comment]
Hi, you can increase the number of genes displayed by changing all occurrences of `maxOptions = 7` to `maxOptions = 10` in `server.R`. I have included a short snippet of the code where this `maxOptions` setting is found.

```
  updateSelectizeInput(session, "sc1a1inp2", choices = names(sc1gene), server = TRUE, 
                       selected = sc1def$gene1, options = list( 
                         maxOptions = 10, create = TRUE, persist = TRUE, render = I(optCrt))) 
```

**Comment by jvelghe** [comment]
This is insightful, thank you!

**Comment by areyoukidneyme** [comment]
Hello!

I'm having some issues with ShinyCell. Normally, after running `makeShinyApp` it will open the Shiny app in my browser, but suddenly it doesn't do that now. I'm getting the same warning discussed above by @jfouyang @baracus37, "Warning: Variable genes for seurat object not found! Have you ran `FindVariableFeatures` or `SCTransform`?" 

<img width="844" alt="Image" src="https://github.com/user-attachments/assets/371ff51a-dea5-489d-bafe-dbd1b634e132" />

When I run `VariableFeatures(seu)` it returns `character(0)`.

I'm using Seurat V4.4.0 and ShinyCell 2.1.0.

Anyone, encountering this problem? Would appreciate any help!

Thank you!
